[project]
name = "calc-fastapi"
version = "0.1.0"
description = "A simple calculator app using Streamlit and FastAPI"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "streamlit>=1.45.1",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "ruff>=0.11.9",
]
